// leave off @2x/@3x
const images = {
  add: require('../Images/add.png'),
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/bg.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  emecoBackground: require('../Images/ignite-logo-transparent.png'),
  emecoLogo: require('../Images/logo_white.png'),
  caretIcon: require('../Images/caret.png'),
  dayIconSelected: require('../Images/sun-selected.png'),
  dayIcon: require('../Images/sun.png'),
  nightIconSelected: require('../Images/moon-selected.png'),
  nightIcon: require('../Images/moon.png'),
  closeIcon: require('../Images/close-icon.png'),
  addTask: require('../Images/add-task.png'),
  collapseIcon: require('../Images/close-icon.png'),
  addTimesheet: require('../Images/add-timesheet.png'),
  arrowDown: require('../Images/arrow-down.png'),
  triangle: require('../Images/Triangle.png'),
  logoutIcon: require('../Images/logout.png'),
  profileIcon: require('../Images/profile-icon.png'),
  documentIcon: require('../Images/document.png'),
  removeIcon: require('../Images/remove.png'),
  dropDownIcon: require('../Images/drop-down-circle.png'),
  dropUpIcon: require('../Images/drop-up-circle.png'),
  clockIcon: require('../Images/access-time.png'),
  whiteBackIcon: require('../Images/back-icon.png'),
  footerOne: require('../Images/footer1.png'),
  footerTwo: require('../Images/footer2.png'),
  sync: require('../Images/sync.png'),
  unSync: require('../Images/un_sync.png'),
  unSyncedSheet: require('../Images/ic-sync-problem-24px.png')
}

export default images
