# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

project 'emeco.xcodeproj'

target 'emeco' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emeco
#  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
#  pod 'React', :path => '../node_modules/react-native'
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

#  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

end

post_install do |installer|
  ## Fix for XCode 12.5
  find_and_replace(
    "../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules",
    "_initializeModules:(NSArray<Class> *)modules"
  )
  find_and_replace(
    "../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
    "RCTBridgeModuleNameForClass(module))",
    "RCTBridgeModuleNameForClass(Class(module)))"
  )

  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    text = File.read(name)
    replace = text.gsub(findstr,replacestr)
    if text != replace
      puts "Fix: " + name
      File.open(name, "w") { |file| file.puts replace }
      STDOUT.flush
    end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

